name: Python Specification

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: exploitation
        run: " echo 'test' "
